[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmd = "npm ci --omit=dev"

[phases.build]
cmd = "npx prisma generate"

[phases.deploy]
cmd = "npm start"

[variables]
NODE_ENV = "production"
